BoxLayout:
    orientation: 'vertical'
#    orientation: 'horizontal'
    Label:
        text:'To clear click the button below'
        color: (1, 1, 0, 1)
    Button:
        text:'Clear'
        on_press: app.clear_box()
    Button:
        text: 'two'
    Button:
        text: 'Greet'
        on_press: app.handle_greet()
        id: output_label
    Label:
        text:'Enter your name'
        color: (1, 1, 0, 1)
    TextInput:
        id: input_name
        text: ''
