BoxLayout:
    orientation: 'vertical'
#    orientation: 'horizontal'
    Label:
        text:'To clear click the button below'
        color: (1, 1, 0, 1)
    Button:
        text:'Clear'
        on_press: app.clear_box()
    TextInput:
        id: input_name
        text: ''
    Button:
        text: 'Greet'
        on_press: app.handle_greet()
    Label:
        text:'Enter your name'
        color: (1, 1, 0, 1)
        id: output_label


